files:
  - source: /**/*.md
    ignore:
      - /fr/
      - /ar/
      - /de/
      - /es/
      - /it/
      - /nl/
      - /pt/
      - /ru/
      - /zh/
      - /ja/
    translation: /%two_letters_code%/%original_path%/%file_name%.md
    content_segmentation: 0